

class AuthService:
    def __init__(self) -> None:
        ...

    async def authenticate(self) -> ...: ...

    async def refresh_tokens(self) -> ...: ...

    async def logout(self) -> ...: ...


class RegistrationService:
    def __init__(self) -> None:
        ...

    async def register(self) -> ...: ...
